package com.test.core_data

import com.test.core_network.dto.ObjectDetailsApiModel

object MockObjectDetails {
    fun createMockObjectDetailsApiModel(objectId: Int, title: String) =
        ObjectDetailsApiModel(
            accessionNumber = "",
            accessionYear = "",
            additionalImages = emptyList(),
            artistAlphaSort = "",
            artistBeginDate = "",
            artistDisplayBio = "",
            artistDisplayName = "",
            artistEndDate = "",
            artistGender = "",
            artistNationality = "",
            artistPrefix = "",
            artistRole = "",
            artistSuffix = "",
            artistULANURL = "",
            artistWikidataURL = "",
            city = "",
            classification = "",
            country = "",
            county = "",
            creditLine = "",
            culture = "",
            department = "",
            dimensions = "",
            dynasty = "",
            excavation = "",
            galleryNumber = "",
            geographyType = "",
            isHighlight = false,
            isPublicDomain = false,
            isTimelineWork = false,
            linkResource = "",
            locale = "",
            locus = "",
            medium = "",
            metadataDate = "",
            objectBeginDate = 0,
            objectDate = "",
            objectEndDate = 0,
            objectID = objectId,
            objectName = "",
            objectURL = "",
            objectWikidataURL = "",
            period = "",
            portfolio = "",
            primaryImage = "",
            primaryImageSmall = "",
            region = "",
            reign = "",
            repository = "",
            rightsAndReproduction = "",
            river = "",
            state = "",
            subregion = "",
            title = title,
        )
}